apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: standard
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
