apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: standard
  labels:
    app: postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
